Set up structure for quering GraphQL
tutturen/potato-store-front pull request #6
Opened 2018-03-03 20:06 UTC by tobinus

The following has been done:
* Use React state and properties in `App` to propagate changes and callbacks to components lower in the hierarchy.
  * Existing GraphQL clients polyfill the promise and fetch API, which are already polyfilled by React. I decided to roll our own solution for better comprehension and simplicity. Most issues I've had (CORS and CSRF) wouldn't have been fixed by external libraries either.
* Create function which encapsulates the GraphQL API. It will send JWT, deal with CORS and CSRF and use the correct URL.
* Add configuration options through environment variables.
* Give up on maintaining the single React test.
* Expand the documentation.

I recommend reading `README.md`.

2018-03-03 22:31 UTC, tobinus commented
I consider myself done with this branch now, so please review and merge.

2018-03-04 14:15 UTC, tutturen requested changes

2018-03-04 14:15 UTC, tutturen commented on src/App.js
> +      const productIndex = prevState.products.indexOf(productID);
Can we use `.includes()` here?

2018-03-04 14:15 UTC, tutturen commented on src/Main/index.js
>      </Switch>
This is not ideal. We should find a better solution to this in the future.

2018-03-04 14:26 UTC, tobinus commented on src/App.js
> +      const productIndex = prevState.products.indexOf(productID);
.includes() does not return the index where the ID is found?

2018-03-04 14:31 UTC, tobinus commented on src/App.js
> +      const productIndex = prevState.products.indexOf(productID);
I'll change to more readable API, but we need the index if we want to remove it.

2018-03-04 14:33 UTC, tutturen approved these changes

2018-03-04 14:33 UTC, tutturen commented on src/App.js
> +      const productIndex = prevState.products.indexOf(productID);
That is a good point.

2018-03-04 14:36 UTC, merged